In [121]:
import pandas as pd
import seaborn as sns
import numpy as np
import pingouin as pg
import matplotlib.pyplot as plt
import statsmodels.api as sm
import statsmodels.formula.api as smf

In [180]:
df = pd.read_csv('B:/Karpov Courses/Stat/Lesson_7/cars.csv')

In [181]:
df.head()

,car_ID,symboling,CarName,fueltype,aspiration,doornumber,carbody,drivewheel,enginelocation,wheelbase,...,enginesize,fuelsystem,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg,price
0,1,3,alfa-romero giulia,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495.0
1,2,3,alfa-romero stelvio,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500.0
2,3,1,alfa-romero Quadrifoglio,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500.0
3,4,2,audi 100 ls,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950.0
4,5,2,audi 100ls,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450.0

In [182]:
df['mark'] = df.CarName.apply(lambda x: x.split()[0])

In [183]:
df.drop(labels = 'CarName',
    axis = 'columns',
    inplace = True)
df.drop(labels = 'car_ID',
    axis = 'columns',
    inplace = True)

In [185]:
df.columns

Index(['symboling', 'fueltype', 'aspiration', 'doornumber', 'carbody',
       'drivewheel', 'enginelocation', 'wheelbase', 'carlength', 'carwidth',
       'carheight', 'curbweight', 'enginetype', 'cylindernumber', 'enginesize',
       'fuelsystem', 'boreratio', 'stroke', 'compressionratio', 'horsepower',
       'peakrpm', 'citympg', 'highwaympg', 'price', 'mark'],
      dtype='object')

In [186]:
df.mark.nunique()

28

In [187]:
df.mark = df.mark.str.lower()

In [188]:
def repl(x,y):
    df.mark.replace(x,y,inplace=True)

In [189]:
repl('maxda', 'mazda')
repl('porsche','porcshce')
repl('toyouta', 'toyota')
repl('vokswagen', 'volkswagen')
repl('vw', 'volkswagen')

In [190]:
cols_to_keep = ['fueltype', 'aspiration','carbody', 'drivewheel', 'wheelbase', 'carlength','carwidth', 'curbweight', 'enginetype', 'cylindernumber', 'enginesize', 'boreratio','horsepower', 'mark', 'price']

In [191]:
df = df[cols_to_keep]

In [192]:
df.corr()

,wheelbase,carlength,carwidth,curbweight,enginesize,boreratio,horsepower,price
wheelbase,1.000000,0.874587,0.795144,0.776386,0.569329,0.488750,0.353294,0.577816
carlength,0.874587,1.000000,0.841118,0.877728,0.683360,0.606454,0.552623,0.682920
carwidth,0.795144,0.841118,1.000000,0.867032,0.735433,0.559150,0.640732,0.759325
curbweight,0.776386,0.877728,0.867032,1.000000,0.850594,0.648480,0.750739,0.835305
enginesize,0.569329,0.683360,0.735433,0.850594,1.000000,0.583774,0.809769,0.874145
boreratio,0.488750,0.606454,0.559150,0.648480,0.583774,1.000000,0.573677,0.553173
horsepower,0.353294,0.552623,0.640732,0.750739,0.809769,0.573677,1.000000,0.808139
price,0.577816,0.682920,0.759325,0.835305,0.874145,0.553173,0.808139,1.000000

In [172]:
round(0.808139, 2)

0.81

In [193]:
df.dtypes

fueltype           object
aspiration         object
carbody            object
drivewheel         object
wheelbase         float64
carlength         float64
carwidth          float64
curbweight          int64
enginetype         object
cylindernumber     object
enginesize          int64
boreratio         float64
horsepower          int64
mark               object
price             float64
dtype: object

In [195]:
df1 = pd.get_dummies(data=df[['fueltype', 'aspiration', 'carbody', 'drivewheel', 'enginetype',
 'cylindernumber',  'mark']], drop_first=True)

In [196]:
new = pd.concat([df.drop(['fueltype', 'aspiration', 'carbody', 'drivewheel', 'enginetype',
 'cylindernumber',  'mark'], axis='columns'), df1], axis=1)

In [197]:
new.head()

,wheelbase,carlength,carwidth,curbweight,enginesize,boreratio,horsepower,price,fueltype_gas,aspiration_turbo,...,mark_nissan,mark_peugeot,mark_plymouth,mark_porcshce,mark_renault,mark_saab,mark_subaru,mark_toyota,mark_volkswagen,mark_volvo
0,88.6,168.8,64.1,2548,130,3.47,111,13495.0,1,0,...,0,0,0,0,0,0,0,0,0,0
1,88.6,168.8,64.1,2548,130,3.47,111,16500.0,1,0,...,0,0,0,0,0,0,0,0,0,0
2,94.5,171.2,65.5,2823,152,2.68,154,16500.0,1,0,...,0,0,0,0,0,0,0,0,0,0
3,99.8,176.6,66.2,2337,109,3.19,102,13950.0,1,0,...,0,0,0,0,0,0,0,0,0,0
4,99.4,176.6,66.4,2824,136,3.19,115,17450.0,1,0,...,0,0,0,0,0,0,0,0,0,0

In [198]:
X = sm.add_constant(new.horsepower)  # добавить константу, чтобы был свободный член
model = sm.OLS(new.price, X)  # говорим модели, что у нас ЗП, а что НП
results = model.fit()  # строим регрессионную прямую
print(results.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                  price   R-squared:                       0.653
Model:                            OLS   Adj. R-squared:                  0.651
Method:                 Least Squares   F-statistic:                     382.2
Date:                Wed, 15 Jun 2022   Prob (F-statistic):           1.48e-48
Time:                        05:45:24   Log-Likelihood:                -2024.0
No. Observations:                 205   AIC:                             4052.
Df Residuals:                     203   BIC:                             4059.
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const      -3721.7615    929.849     -4.003      0.000   -5555.163   -1888.360
horsepower   163.2631      8.351     19.549      0.000     146.796     179.730
==============================================================================
Omnibus:                       47.741   Durbin-Watson:                   0.792
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               91.702
Skew:                           1.141   Prob(JB):                     1.22e-20
Kurtosis:                       5.352   Cond. No.                         314.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [206]:
results = smf.ols('price ~ wheelbase + carlength+carwidth+curbweight+enginesize+boreratio+\
horsepower+fueltype_gas+aspiration_turbo+mark_nissan+mark_peugeot+mark_plymouth+mark_porcshce\
+mark_renault+mark_saab+mark_subaru+mark_toyota+mark_volkswagen+mark_volvo', new).fit()
print(results.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                  price   R-squared:                       0.878
Model:                            OLS   Adj. R-squared:                  0.866
Method:                 Least Squares   F-statistic:                     70.18
Date:                Wed, 15 Jun 2022   Prob (F-statistic):           6.04e-74
Time:                        18:02:22   Log-Likelihood:                -1916.7
No. Observations:                 205   AIC:                             3873.
Df Residuals:                     185   BIC:                             3940.
Df Model:                          19
Covariance Type:            nonrobust
====================================================================================
                       coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------------
Intercept        -2.862e+04   1.22e+04     -2.353      0.020   -5.26e+04   -4618.797
wheelbase          219.1030     98.460      2.225      0.027      24.854     413.352
carlength            0.0385     55.841      0.001      0.999    -110.128     110.205
carwidth            78.1268    229.720      0.340      0.734    -375.080     531.334
curbweight           4.6629      1.555      2.999      0.003       1.595       7.730
enginesize          71.1182     13.726      5.181      0.000      44.038      98.198
boreratio        -1979.8990   1339.611     -1.478      0.141   -4622.777     662.979
horsepower          28.0088     15.601      1.795      0.074      -2.770      58.788
fueltype_gas     -1093.7413   1054.112     -1.038      0.301   -3173.366     985.884
aspiration_turbo  -523.8144    767.177     -0.683      0.496   -2037.356     989.727
mark_nissan      -2686.0528    798.236     -3.365      0.001   -4260.868   -1111.237
mark_peugeot     -4886.9769   1272.851     -3.839      0.000   -7398.146   -2375.808
mark_plymouth    -2265.2848   1175.612     -1.927      0.056   -4584.615      54.045
mark_porcshce     1.052e+04   1915.095      5.492      0.000    6740.210    1.43e+04
mark_renault     -3761.4270   2197.539     -1.712      0.089   -8096.885     574.031
mark_saab          -82.2696   1406.295     -0.059      0.953   -2856.707    2692.167
mark_subaru      -1477.3304   1080.981     -1.367      0.173   -3609.965     655.305
mark_toyota      -3012.1901    635.801     -4.738      0.000   -4266.543   -1757.837
mark_volkswagen  -1634.7355    961.037     -1.701      0.091   -3530.736     261.265
mark_volvo       -1350.8952   1118.513     -1.208      0.229   -3557.575     855.785
==============================================================================
Omnibus:                       37.714   Durbin-Watson:                   1.024
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              104.465
Skew:                           0.763   Prob(JB):                     2.07e-23
Kurtosis:                       6.147   Cond. No.                     1.56e+05
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.56e+05. This might indicate that there are
strong multicollinearity or other numerical problems.

In [ ]:
'wheelbase + carlength+carwidth+curbweight+enginesize+boreratio+horsepower+fueltype_gas\
+aspiration_turbo

In [205]:
results = smf.ols('price ~ wheelbase + carlength+carwidth+curbweight+enginesize\
+boreratio+horsepower+fueltype_gas', new).fit()
print(results.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                  price   R-squared:                       0.825
Model:                            OLS   Adj. R-squared:                  0.818
Method:                 Least Squares   F-statistic:                     115.5
Date:                Wed, 15 Jun 2022   Prob (F-statistic):           6.40e-70
Time:                        05:57:43   Log-Likelihood:                -1953.9
No. Observations:                 205   AIC:                             3926.
Df Residuals:                     196   BIC:                             3956.
Df Model:                           8
Covariance Type:            nonrobust
================================================================================
                   coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------
Intercept    -3.781e+04   1.33e+04     -2.834      0.005   -6.41e+04   -1.15e+04
wheelbase      100.9851     97.799      1.033      0.303     -91.889     293.859
carlength      -34.6788     54.713     -0.634      0.527    -142.581      73.223
carwidth       467.6695    255.144      1.833      0.068     -35.510     970.849
curbweight       1.6334      1.642      0.995      0.321      -1.605       4.872
enginesize      82.7914     12.637      6.551      0.000      57.869     107.714
boreratio    -1120.6730   1196.513     -0.937      0.350   -3480.366    1239.020
horsepower      67.4586     14.133      4.773      0.000      39.587      95.330
fueltype_gas -1822.8246    977.659     -1.864      0.064   -3750.907     105.257
==============================================================================
Omnibus:                       28.134   Durbin-Watson:                   0.832
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               62.866
Skew:                           0.628   Prob(JB):                     2.23e-14
Kurtosis:                       5.404   Cond. No.                     1.47e+05
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.47e+05. This might indicate that there are
strong multicollinearity or other numerical problems.